// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Logistics.DbAccess
{
    public partial class Cities
    {
        public Cities()
        {
            LogisticsCenters = new HashSet<LogisticsCenters>();
            RoutesEndCity = new HashSet<Routes>();
            RoutesStartCity = new HashSet<Routes>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime DateUpdated { get; set; }

        public virtual ICollection<LogisticsCenters> LogisticsCenters { get; set; }
        public virtual ICollection<Routes> RoutesEndCity { get; set; }
        public virtual ICollection<Routes> RoutesStartCity { get; set; }
    }
}