// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Logistics.DbAccess
{
    public partial class LogisticsCenters
    {
        public int Id { get; set; }
        public int CityId { get; set; }
        public DateTime DateUpdated { get; set; }

        public virtual Cities City { get; set; }
    }
}