// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Logistics.DbAccess
{
    public partial class Routes
    {
        public int Id { get; set; }
        public int StartCityId { get; set; }
        public int EndCityId { get; set; }
        public DateTime DateUpdated { get; set; }
        public decimal Distance { get; set; }

        public virtual Cities EndCity { get; set; }
        public virtual Cities StartCity { get; set; }
    }
}